
services:
  - type: web
    plan: free
    name: dynamic-pricing
    runtime: python
    buildCommand: "./backend/build.sh"
    startCommand: "cd backend && python -m gunicorn dynamic_pricing_project.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4